---
substitutions:
  board: esp32dev

esp32:
  board: ${board}
  framework:
    type: arduino
    #version: recommended

packages:
  base: !include common-base.yaml
  #network: !include common/network-idf.yaml
